name: "CI/CD pipeline for two tier application_employee management portal"

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show System Information
        run: |
          pwd
          ls -la
          whoami
          hostname
          free -m
          cat /etc/os-release
          uname -a
          lscpu
          docker --version
          docker compose version

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build Backend Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USER }}/employee-portal-backend:latest ./backend

      - name: Frontend Image Building
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USER }}/employee-portal-frontend:latest ./frontend

      - name: Push Backend Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USER }}/employee-portal-backend:latest

      - name: Push Frontend Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USER }}/employee-portal-frontend:latest

      - name: Debug Check Secrets
        run: |
          echo "=== SECRET CHECK ==="
          if [ -z "${EC2_HOST}" ]; then echo "❌ EC2_HOST_ADDRESS is MISSING/EMPTY"; else echo "✅ EC2_HOST_ADDRESS is set (length: ${#EC2_HOST})"; fi
          if [ -z "${EC2_USER}" ]; then echo "❌ EC2_USERNAME is MISSING/EMPTY"; else echo "✅ EC2_USERNAME is set (length: ${#EC2_USER})"; fi
          if [ -z "${EC2_KEY}" ]; then echo "❌ EC2_SSH_KEY is MISSING/EMPTY"; else echo "✅ EC2_SSH_KEY is set (length: ${#EC2_KEY})"; fi
          if [ -z "${DOCKER_USER}" ]; then echo "❌ DOCKERHUB_USER is MISSING/EMPTY"; else echo "✅ DOCKERHUB_USER is set (length: ${#DOCKER_USER})"; fi
        env:
          EC2_HOST: ${{ secrets.EC2_HOST_ADDRESS }}
          EC2_USER: ${{ secrets.EC2_USERNAME }}
          EC2_KEY: ${{ secrets.EC2_SSH_KEY }}
          DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_ADDRESS }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd Docker-Project-
            docker compose down
            docker pull ${{ secrets.DOCKERHUB_USER }}/employee-portal-backend:latest
            docker pull ${{ secrets.DOCKERHUB_USER }}/employee-portal-frontend:latest
            docker compose up -d
            docker ps
